# Generated by Django 6.0.2 on 2026-03-18 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(default='Bohol', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='accounts.campus')),
            ],
            options={
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DEPT_SEC', 'Department Secretary'), ('CAMPUS_SEC', 'Campus Secretary'), ('DEAN', 'Dean'), ('DIRECTOR', 'Director'), ('PRESIDENT', 'President'), ('BUDGET', 'Budget Officer'), ('CASHIER', 'Cashier'), ('ADMIN', 'Administrator')], max_length=20)),
                ('preference', models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('NO_PREPAYMENT', 'No Prepayment')], max_length=20)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('on_travel', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve all new accounts')),
                ('is_active', models.BooleanField(default=True, help_text='Account can be deactivated')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to='accounts.user')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.college')),
            ],
        ),
    ]
