# Generated by Django 6.0.2 on 2026-02-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department_alter_user_campus_college_and_more'),
        ('travel_app', '0004_travelordercomment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
