# Generated by Django 6.0.2 on 2026-03-18 04:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryOfTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_meals_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_nights', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_transportation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_other_expenses', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file', models.FileField(blank=True, null=True, upload_to='itinerary_documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=20, unique=True)),
                ('region_name', models.CharField(max_length=100)),
                ('meal_rate', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(0)])),
                ('lodging_rate', models.IntegerField(default=900, validators=[django.core.validators.MinValueValidator(0)])),
                ('incidental_rate', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['region_code'],
            },
        ),
        migrations.CreateModel(
            name='LetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending President Approval'), ('APPROVED', 'Approved by President'), ('REJECTED', 'Rejected by President')], default='PENDING', max_length=20)),
                ('justification', models.TextField(max_length=5000)),
                ('file', models.FileField(blank=True, null=True, upload_to='letter_requests/%Y/%m/')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('president_remarks', models.TextField(blank=True, max_length=500)),
                ('approved_by_president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_approved_letters', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('is_out_of_province', models.BooleanField(default=False)),
                ('purpose', models.TextField(max_length=5000)),
                ('initiating_office', models.CharField(max_length=200)),
                ('funding_office', models.CharField(blank=True, max_length=200)),
                ('prepayment_option', models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('NOT', 'No Prepayment')], max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_travels', to='travel_app.itineraryoftravel')),
                ('letter_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_travels', to='travel_app.letterrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TRAVEL_CREATED', 'Travel Created'), ('TRAVEL_APPROVED', 'Travel Approved'), ('TRAVEL_REJECTED', 'Travel Rejected'), ('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('FINANCIAL_APPROVED', 'Financial Documents Approved'), ('CHECK_READY', 'Check Ready for Pickup'), ('LIQUIDATION_REQUIRED', 'Liquidation Report Required'), ('APPROVAL_NEEDED', 'Approval Needed'), ('COMMENT_ADDED', 'Comment Added')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
                ('official_travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='travel_app.officialtravel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_to_be_reimbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='liquidation_reports/%Y/%m/')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_liquidations', to='accounts.user')),
                ('official_travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation_report', to='travel_app.officialtravel')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DV', 'Disbursement Voucher'), ('BURS', 'Budget Utilization Request and Status')], max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Budget Officer Approval'), ('APPROVED', 'Approved by Budget Officer'), ('REJECTED', 'Rejected by Budget Officer'), ('REPLACED', 'Replaced by Newer Version')], default='ACTIVE', max_length=50)),
                ('file', models.FileField(upload_to='financial_documents/%Y/%m/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_financial_docs', to='accounts.user')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_financial_docs', to='accounts.user')),
                ('official_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_documents', to='travel_app.officialtravel')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('REIMBURSEMENT', 'Reimbursement'), ('REFUND_RETURN', 'Refund Return')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Release'), ('RELEASED', 'Check Released'), ('CLAIMED', 'Check Claimed by Employee')], default='PENDING', max_length=20)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_checks', to='accounts.user')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_checks', to='accounts.user')),
                ('official_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_releases', to='travel_app.officialtravel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='travel_app.itineraryoftravel')),
            ],
        ),
        migrations.AddField(
            model_name='officialtravel',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_travels', to='travel_app.payroll'),
        ),
        migrations.CreateModel(
            name='PayrollParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='participant_groups', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='participants_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='travel_app.payrollparticipants'),
        ),
        migrations.AddField(
            model_name='officialtravel',
            name='participants_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_travels', to='travel_app.payrollparticipants'),
        ),
        migrations.CreateModel(
            name='PostTravelDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REPORT', 'Post Activity Report Form'), ('COMPLETED', 'Certificate of Travel Completed'), ('RECEIPTS', 'Certificate of Not Requiring Receipts'), ('APPEARANCE', 'Certificate of Appearance'), ('ACTUAL_ITINERARY', 'Actual Itinerary of Travel')], max_length=20)),
                ('file', models.FileField(upload_to='post_travel_documents/%Y/%m/')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('official_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_travel_documents', to='travel_app.officialtravel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_post_travel_docs', to='accounts.user')),
            ],
            options={
                'ordering': ['-submit_date'],
            },
        ),
        migrations.AddField(
            model_name='itineraryoftravel',
            name='region_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_app.regionrate'),
        ),
        migrations.CreateModel(
            name='TravelInitiationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MEMORANDUM', 'Memo'), ('LETTER', 'Request Letter')], max_length=20)),
                ('issuer', models.CharField(help_text='Who issued the memo/letter', max_length=100)),
                ('date_issued', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('file', models.FileField(help_text='Upload the actual memo or request letter', upload_to='initiation_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_documents', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING_DEAN', 'Pending Dean Approval'), ('PENDING_DIRECTOR', 'Pending Director Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_DEAN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dean_approval_date', models.DateTimeField(blank=True, null=True)),
                ('dean_remarks', models.TextField(blank=True, max_length=500)),
                ('director_approval_date', models.DateTimeField(blank=True, null=True)),
                ('director_remarks', models.TextField(blank=True, max_length=500)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by_dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_approved_orders', to='accounts.user')),
                ('approved_by_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_orders', to='accounts.user')),
                ('created_by', models.ForeignKey(help_text='Employee or Secretary who created this', on_delete=django.db.models.deletion.CASCADE, related_name='created_travel_orders', to='accounts.user')),
                ('initiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_orders', to='travel_app.travelinitiationdocument')),
            ],
        ),
        migrations.AddField(
            model_name='officialtravel',
            name='travel_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_travels', to='travel_app.travelorder'),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='travel_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_letters', to='travel_app.travelorder'),
        ),
        migrations.CreateModel(
            name='TravelOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_comments', to='accounts.user')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='travel_app.travelordercomment')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travel_app.travelorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='e.g., 2026')),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total allocated budget for the year', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='accounts.campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='accounts.college')),
            ],
            options={
                'ordering': ['-fiscal_year'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('college', 'fiscal_year'), name='unique_college_fiscal_year'), models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'fiscal_year'), name='unique_campus_fiscal_year')],
            },
        ),
    ]
