# Generated by Django 6.0.2 on 2026-03-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('COLLEGE', 'College-Level'), ('CAMPUS', 'Campus-Level')], default='COLLEGE', max_length=10)),
                ('year', models.IntegerField(help_text='Fiscal year, e.g. 2026')),
                ('college_budget_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount allocated to EACH college for this source/year', max_digits=12)),
                ('campus_budget_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total campus-wide pool for this source/year', max_digits=12)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Source',
                'verbose_name_plural': 'Budget Sources',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'College Budget Usage',
                'verbose_name_plural': 'College Budget Usage Records',
                'ordering': ['-year', 'college__name'],
            },
        ),
        migrations.CreateModel(
            name='CampusBudgetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Campus Budget Usage',
                'verbose_name_plural': 'Campus Budget Usage Records',
                'ordering': ['-year', 'campus__name'],
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "CHED Regional Conference 2026"', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('COLLEGE', 'Single College'), ('CAMPUS', 'Cross-College / Campus-Wide')], default='COLLEGE', max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Group',
                'verbose_name_plural': 'Event Groups',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('TRAVEL_ORDER', 'Travel Order'), ('ITINERARY', 'Itinerary of Travel'), ('DV', 'Disbursement Voucher'), ('BURS', 'Budget Utilization Request and Status'), ('RECEIPTS', 'Official Receipts'), ('CERTIFICATE', 'Certificate of Appearance / Completion'), ('POST_REPORT', 'Post-Activity Report'), ('LETTER_REQUEST', 'Letter Request (Out-of-Province)')], max_length=30)),
                ('file', models.FileField(upload_to='travel_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('extracted_destination', models.CharField(blank=True, max_length=200)),
                ('extracted_start_date', models.DateField(blank=True, null=True)),
                ('extracted_end_date', models.DateField(blank=True, null=True)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extracted_purpose', models.TextField(blank=True, max_length=500)),
                ('extracted_num_travelers', models.IntegerField(blank=True, null=True)),
                ('extraction_raw', models.TextField(blank=True, help_text='Raw JSON response from Ollama for debugging.')),
                ('extraction_attempted', models.BooleanField(default=False)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Secretary confirmed extracted data is correct. Used by stats engine.')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Travel Document',
                'verbose_name_plural': 'Travel Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_snapshot', models.CharField(blank=True, help_text='College name at time of travel. Used for scope detection and historical stats.', max_length=100)),
                ('campus_snapshot', models.CharField(blank=True, help_text='Campus name at time of travel.', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Travel Participant',
                'verbose_name_plural': 'Travel Participants',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(max_length=2000)),
                ('is_out_of_province', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('COLLEGE', 'College-Level'), ('CAMPUS', 'Campus-Level')], default='COLLEGE', help_text='Auto-detected from participants. COLLEGE = same college, CAMPUS = cross-college.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_deducted', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of amount deducted from budget source. Preserved even if source changes.', max_digits=12)),
                ('budget_tagged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Travel Record',
                'verbose_name_plural': 'Travel Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='budgetallocation',
            name='unique_college_fiscal_year',
        ),
        migrations.RemoveConstraint(
            model_name='budgetallocation',
            name='unique_campus_fiscal_year',
        ),
        migrations.RemoveField(
            model_name='financialdocuments',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='financialdocuments',
            name='official_travel',
        ),
        migrations.RemoveField(
            model_name='financialdocuments',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='itineraryoftravel',
            name='region_rate',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='officialtravel',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='letterrequest',
            name='approved_by_president',
        ),
        migrations.RemoveField(
            model_name='letterrequest',
            name='travel_order',
        ),
        migrations.RemoveField(
            model_name='officialtravel',
            name='letter_request',
        ),
        migrations.RemoveField(
            model_name='liquidationreport',
            name='official_travel',
        ),
        migrations.RemoveField(
            model_name='liquidationreport',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='officialtravel',
            name='participants_group',
        ),
        migrations.RemoveField(
            model_name='officialtravel',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='officialtravel',
            name='travel_order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='official_travel',
        ),
        migrations.RemoveField(
            model_name='posttraveldocuments',
            name='official_travel',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='participants_group',
        ),
        migrations.RemoveField(
            model_name='payrollparticipants',
            name='users',
        ),
        migrations.RemoveField(
            model_name='posttraveldocuments',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='travelinitiationdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='initiation',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='approved_by_dean',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='approved_by_director',
        ),
        migrations.RemoveField(
            model_name='travelorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='travelordercomment',
            name='travel_order',
        ),
        migrations.RemoveField(
            model_name='travelordercomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='travelordercomment',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRAVEL_CREATED', 'Travel Created'), ('BUDGET_TAGGED', 'Budget Source Tagged'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('BUDGET_LOW', 'Budget Running Low'), ('BUDGET_EXHAUSTED', 'Budget Exhausted'), ('DUPLICATE_DETECTED', 'Possible Duplicate Travel Detected'), ('EXTRACTION_DONE', 'AI Extraction Complete — Please Review'), ('OVER_BUDGET', 'Travel Exceeds Budget')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='budgetsource',
            unique_together={('name', 'year', 'scope')},
        ),
        migrations.AddField(
            model_name='budgetusage',
            name='budget_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_usage', to='travel_app.budgetsource'),
        ),
        migrations.AddField(
            model_name='budgetusage',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_usage', to='accounts.college'),
        ),
        migrations.AddField(
            model_name='campusbudgetusage',
            name='budget_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_usage', to='travel_app.budgetsource'),
        ),
        migrations.AddField(
            model_name='campusbudgetusage',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_usage', to='accounts.campus'),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_groups', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_travel_docs', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_travel_docs', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='travelparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_participations', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='budget_source',
            field=models.ForeignKey(blank=True, help_text='Assigned by Secretary after travel is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_records', to='travel_app.budgetsource'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='budget_tagged_by',
            field=models.ForeignKey(blank=True, help_text='Secretary who assigned the budget source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_tagged_travels', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_travels', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='travelrecord',
            name='event_group',
            field=models.ForeignKey(blank=True, help_text='Links this travel to others that are part of the same event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_records', to='travel_app.eventgroup'),
        ),
        migrations.AddField(
            model_name='travelparticipant',
            name='travel_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='travel_app.travelrecord'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='travel_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel_app.travelrecord'),
        ),
        migrations.AddField(
            model_name='notification',
            name='travel_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='travel_app.travelrecord'),
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='college',
        ),
        migrations.DeleteModel(
            name='CheckRelease',
        ),
        migrations.DeleteModel(
            name='FinancialDocuments',
        ),
        migrations.DeleteModel(
            name='RegionRate',
        ),
        migrations.DeleteModel(
            name='ItineraryOfTravel',
        ),
        migrations.DeleteModel(
            name='LetterRequest',
        ),
        migrations.DeleteModel(
            name='LiquidationReport',
        ),
        migrations.DeleteModel(
            name='OfficialTravel',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollParticipants',
        ),
        migrations.DeleteModel(
            name='PostTravelDocuments',
        ),
        migrations.DeleteModel(
            name='TravelInitiationDocument',
        ),
        migrations.DeleteModel(
            name='TravelOrder',
        ),
        migrations.DeleteModel(
            name='TravelOrderComment',
        ),
        migrations.AlterUniqueTogether(
            name='budgetusage',
            unique_together={('college', 'budget_source', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='campusbudgetusage',
            unique_together={('campus', 'budget_source', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='travelparticipant',
            unique_together={('travel_record', 'user')},
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
    ]
