# Generated by Django 6.0.2 on 2026-03-21 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0002_budgetsource_budgetusage_campusbudgetusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='funding_college',
            field=models.ForeignKey(blank=True, help_text='Set by Campus Secretary when cross-college travel is funded by a specific college', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_travels', to='accounts.college'),
        ),
    ]
