# Generated by Django 6.0.2 on 2026-02-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_itineraryoftravel_departure_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryoftravel',
            name='departure_datetime',
        ),
        migrations.RemoveField(
            model_name='itineraryoftravel',
            name='return_datetime',
        ),
    ]
