# Generated by Django 6.0.2 on 2026-02-17 05:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_department_alter_user_campus_college_and_more'),
        ('travel_app', '0003_remove_itineraryoftravel_departure_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='accounts.college'),
        ),
        migrations.AlterField(
            model_name='checkrelease',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_checks', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='checkrelease',
            name='release_type',
            field=models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('REIMBURSEMENT', 'Reimbursement'), ('REFUND_RETURN', 'Refund Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialdocuments',
            name='file',
            field=models.FileField(upload_to='financial_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='financialdocuments',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Budget Officer Approval'), ('APPROVED', 'Approved by Budget Officer'), ('REJECTED', 'Rejected by Budget Officer'), ('REPLACED', 'Replaced by Newer Version')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='estimated_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='estimated_meals_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='estimated_nights',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='estimated_other_expenses',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='estimated_transportation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='itinerary_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='itineraryoftravel',
            name='region_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel_app.regionrate'),
        ),
        migrations.AlterField(
            model_name='letterrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='letter_requests/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='letterrequest',
            name='justification',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='liquidationreport',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidationreport',
            name='amount_to_be_reimbursed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidationreport',
            name='cash_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='liquidationreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='liquidation_reports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='liquidationreport',
            name='total_amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRAVEL_CREATED', 'Travel Created'), ('TRAVEL_APPROVED', 'Travel Approved'), ('TRAVEL_REJECTED', 'Travel Rejected'), ('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('FINANCIAL_APPROVED', 'Financial Documents Approved'), ('CHECK_READY', 'Check Ready for Pickup'), ('LIQUIDATION_REQUIRED', 'Liquidation Report Required'), ('APPROVAL_NEEDED', 'Approval Needed'), ('COMMENT_ADDED', 'Comment Added')], max_length=30),
        ),
        migrations.AlterField(
            model_name='officialtravel',
            name='funding_office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='officialtravel',
            name='initiating_office',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='officialtravel',
            name='letter_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_travels', to='travel_app.letterrequest'),
        ),
        migrations.AlterField(
            model_name='officialtravel',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_travels', to='travel_app.payroll'),
        ),
        migrations.AlterField(
            model_name='posttraveldocuments',
            name='file',
            field=models.FileField(upload_to='post_travel_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='regionrate',
            name='incidental_rate',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='regionrate',
            name='lodging_rate',
            field=models.IntegerField(default=900, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='regionrate',
            name='meal_rate',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='regionrate',
            name='region_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('college__isnull', False)), fields=('college', 'fiscal_year'), name='unique_college_fiscal_year'),
        ),
        migrations.AddConstraint(
            model_name='budgetallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', False)), fields=('campus', 'fiscal_year'), name='unique_campus_fiscal_year'),
        ),
        migrations.AddField(
            model_name='travelordercomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_comments', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='travelordercomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='travel_app.travelordercomment'),
        ),
        migrations.AddField(
            model_name='travelordercomment',
            name='travel_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='travel_app.travelorder'),
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='allocation_type',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='budgetallocation',
            name='spent_budget',
        ),
    ]
