# Generated by Django 6.0.2 on 2026-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_travelrecord_funding_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldocument',
            name='detected_doc_type',
            field=models.CharField(blank=True, help_text='Document type as detected by AI (may differ from user selection)', max_length=30),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extraction_confidence',
            field=models.CharField(blank=True, help_text='high / medium / low', max_length=10),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extraction_status',
            field=models.CharField(default='pending', help_text='pending / processing / done / failed', max_length=20),
        ),
    ]
