# Generated by Django 6.0.2 on 2026-03-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0004_traveldocument_detected_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldocument',
            name='extracted_num_travelers',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='extraction_attempted',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='extraction_raw',
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='amount_confirmed',
            field=models.BooleanField(default=False, help_text='User reviewed and confirmed the extracted amount. Triggers budget deduction.'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='amount_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='amount_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_confirmed_docs', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extracted_traveler_names',
            field=models.JSONField(blank=True, default=list, help_text='List of traveler names extracted from Travel Order'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='detected_doc_type',
            field=models.CharField(blank=True, help_text='Document type as detected by AI', max_length=30),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Extracted amount from BURS or Itinerary. Confirmed by user before deduction.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Secretary confirmed this document is valid.'),
        ),
    ]
