# Generated by Django 6.0.2 on 2026-04-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_remove_traveldocument_extracted_num_travelers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='scope_overridden',
            field=models.BooleanField(default=False, help_text='If True, scope was manually set and will not be auto-detected from participants.'),
        ),
    ]
