# Generated by Django 6.0.2 on 2026-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_travelrecord_scope_overridden'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='unregistered_travelers',
            field=models.JSONField(blank=True, default=list, help_text='Names of travelers not registered in the system at time of creation.'),
        ),
    ]
