# Generated by Django 6.0.2 on 2026-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_travelrecord_unregistered_travelers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsource',
            name='campus_budget_amount',
        ),
        migrations.RemoveField(
            model_name='budgetsource',
            name='college_budget_amount',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='amount_confirmed',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='amount_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='amount_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='detected_doc_type',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='extracted_traveler_names',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='extraction_confidence',
        ),
        migrations.RemoveField(
            model_name='traveldocument',
            name='extraction_status',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='scope_overridden',
        ),
        migrations.RemoveField(
            model_name='travelrecord',
            name='unregistered_travelers',
        ),
        migrations.AddField(
            model_name='budgetsource',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount allocated per college (COLLEGE scope) or total campus pool (CAMPUS scope)', max_digits=12),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extracted_num_travelers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extraction_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='extraction_raw',
            field=models.TextField(blank=True, help_text='Raw JSON response from Ollama for debugging.'),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='traveldocument',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Secretary confirmed extracted data is correct. Used by stats engine.'),
        ),
    ]
