# Generated by Django 6.0.2 on 2026-04-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0008_remove_budgetsource_campus_budget_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('TRAVEL_ORDER', 'Travel Order'), ('ITINERARY', 'Itinerary of Travel'), ('DV', 'Disbursement Voucher'), ('BURS', 'Budget Utilization Request and Status'), ('RECEIPTS', 'Official Receipts'), ('CERTIFICATE', 'Certificate of Appearance / Completion'), ('POST_REPORT', 'Post-Activity Report'), ('LETTER_REQUEST', 'Letter Request (Out-of-Province)')], max_length=30)),
                ('file', models.FileField(upload_to='participant_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('extracted_destination', models.CharField(blank=True, max_length=200)),
                ('extracted_start_date', models.DateField(blank=True, null=True)),
                ('extracted_end_date', models.DateField(blank=True, null=True)),
                ('extracted_purpose', models.TextField(blank=True, max_length=500)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount extracted from Itinerary. Used for per-person expense tracking.', max_digits=12, null=True)),
                ('extraction_attempted', models.BooleanField(default=False)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('extraction_raw', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_participant_docs', to='accounts.user')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel_app.travelparticipant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_participant_docs', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Participant Document',
                'verbose_name_plural': 'Participant Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='TravelDocument',
        ),
    ]
