# Generated by Django 6.0.2 on 2026-04-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0009_participantdocument_delete_traveldocument'),
    ]

    operations = [
        # First, remove the old unique_together constraint if it exists
        migrations.AlterUniqueTogether(
            name='budgetusage',
            unique_together=set(),
        ),
        
        # Add the user field
        migrations.AddField(
            model_name='budgetusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_usage', to='accounts.user'),
        ),
        
        # Now add the new unique_together constraint
        migrations.AlterUniqueTogether(
            name='budgetusage',
            unique_together={('user', 'budget_source', 'year')},
        ),
        
        # The rename operations are commented out because the columns already exist in your database
        # migrations.RenameField(
        #     model_name='travelparticipant',
        #     old_name='campus_snapshot',
        #     new_name='campus_name',
        # ),
        # migrations.RenameField(
        #     model_name='travelparticipant',
        #     old_name='college_snapshot',
        #     new_name='college_name',
        # ),
        
        migrations.AlterModelOptions(
            name='budgetusage',
            options={'ordering': ['-year', 'user__last_name'], 'verbose_name': 'Budget Usage', 'verbose_name_plural': 'Budget Usage Records'},
        ),
        migrations.AlterField(
            model_name='budgetusage',
            name='budget_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='travel_app.budgetsource'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='amount_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='budget_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_records', to='travel_app.budgetsource'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='budget_tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_tagged_travels', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_records', to='travel_app.eventgroup'),
        ),
        migrations.AlterField(
            model_name='travelrecord',
            name='funding_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_travels', to='accounts.college'),
        ),
        migrations.DeleteModel(
            name='CampusBudgetUsage',
        ),
        migrations.RemoveField(
            model_name='budgetusage',
            name='college',
        ),
    ]