# Generated by Django 6.0.2 on 2026-04-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0010_alter_budgetusage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelparticipant',
            old_name='campus_snapshot',
            new_name='campus_name',
        ),
        migrations.RenameField(
            model_name='travelparticipant',
            old_name='college_snapshot',
            new_name='college_name',
        ),
    ]
