# Generated by Django 6.0.2 on 2026-04-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0011_rename_campus_snapshot_travelparticipant_campus_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsource',
            options={'ordering': ['-fiscal_year', 'budget_name'], 'verbose_name': 'Budget Source', 'verbose_name_plural': 'Budget Sources'},
        ),
        migrations.RenameField(
            model_name='budgetsource',
            old_name='name',
            new_name='budget_name',
        ),
        migrations.RenameField(
            model_name='budgetsource',
            old_name='scope',
            new_name='budget_scope',
        ),
        migrations.RenameField(
            model_name='budgetsource',
            old_name='year',
            new_name='fiscal_year',
        ),
        migrations.AlterUniqueTogether(
            name='budgetsource',
            unique_together={('budget_name', 'fiscal_year', 'budget_scope')},
        ),
    ]
