# Generated by Django 6.0.2 on 2026-04-26 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0012_alter_budgetsource_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_name', models.CharField(help_text='Name as extracted from travel order', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to='accounts.user')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to='accounts.user')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='travel_app.travelrecord')),
            ],
            options={
                'verbose_name': 'Travel Invite',
                'verbose_name_plural': 'Travel Invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
