# Generated by Django 6.0.2 on 2026-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0013_travelinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrecord',
            name='unregistered_travelers',
            field=models.TextField(blank=True, default='', help_text='JSON list of unregistered traveler names extracted from travel order'),
        ),
    ]
