# Generated by Django 6.0.2 on 2026-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0014_travelrecord_unregistered_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdocument',
            name='doc_type',
            field=models.CharField(choices=[('TRAVEL_ORDER', 'Travel Order'), ('ITINERARY', 'Itinerary of Travel'), ('ACTUAL_ITINERARY', 'Actual Itinerary of Travel'), ('DV', 'Disbursement Voucher'), ('BURS', 'Budget Utilization Request and Status'), ('RECEIPTS', 'Official Receipts'), ('CERTIFICATE', 'Certificate of Appearance / Completion'), ('POST_REPORT', 'Post-Activity Report'), ('LETTER_REQUEST', 'Letter Request (Out-of-Province)')], max_length=30),
        ),
    ]
