# Generated by Django 6.0.2 on 2026-04-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0015_alter_participantdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelparticipant',
            name='is_registered',
            field=models.BooleanField(default=True, help_text='True = has a user account. False = unregistered participant.'),
        ),
        migrations.AddField(
            model_name='travelparticipant',
            name='liquidated_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount already budget-adjusted via actual itinerary. Used to compute delta on re-liquidation.', max_digits=12),
        ),
        migrations.AddField(
            model_name='travelparticipant',
            name='name',
            field=models.CharField(blank=True, help_text='Name for unregistered participants. Leave blank for registered users.', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_participations', to='accounts.user'),
        ),
    ]
