# Generated by Django 6.0.2 on 2026-04-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0016_travelparticipant_is_registered_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='travelparticipant',
            unique_together=set(),
        ),
    ]
