# Generated by Django 6.0.2 on 2026-05-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0017_alter_travelparticipant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrecord',
            name='event_group',
        ),
        migrations.DeleteModel(
            name='EventGroup',
        ),
    ]
