# Generated by Django 6.0.2 on 2026-05-03 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0018_remove_travelrecord_event_group_delete_eventgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsource',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College this budget belongs to (COLLEGE scope only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_sources', to='accounts.college'),
        ),
    ]
