# Generated by Django 6.0.2 on 2026-05-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('travel_app', '0019_budgetsource_college'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetsource',
            unique_together={('budget_name', 'fiscal_year', 'budget_scope', 'college')},
        ),
    ]
